# Группы кулдаунов.
cooldown_groups:
  # Дефолтная группа вагонеток.
  # Вы можете создавать свои группы по данному образцу.
  minecarts:
    # Факторы работы. Указываются через ;
    # Доступные факторы:
    # RIGHT_CLICK_AIR - если предметом кликнули правой кнопкой по воздуху
    # RIGHT_CLICK_BLOCK - если предметом кликнули правой кнопкой по блоку
    # CONSUME - если предмет был съеден
    # ENTITY_INTERACT - если предметом кликнули по сущности
    work_factors: RIGHT_CLICK_BLOCK
    # Сколько устанавливать кулдаун предметам (в тиках).
    # Если установлено значение менее 1 - группа отмечается некорректной.
    cooldown: 20
    # В каких мирах активен запрет.
    # Если пусто или - '*' в списке - будет активно во всех мирах.
    active_worlds:
      - '*'
    # На какие предметы необходимо накладывать кулдаун.
    items:
      - MINECART
      - TNT_MINECART
      - CHEST_MINECART
      - HOPPER_MINECART
      - COMMAND_MINECART
      - FURNACE_MINECART
    # Если материалом будет зелье - какие эффекты у него должны быть, чтобы подействовал кулдаун?
    # Для ванильных зелий
    potion_base:
      - '*'
    # Для кастомных зелий
    # Если пусто или - '*' в списке - будет распространяться на любое зелье
    potion_effects:
      - '*'
    # Должен ли плагин игнорировать уже имеющийся кулдаун у предмета?
    # Если включено - плагин не будет накладывать кулдаун даже если у него уже есть кулдаун.
    # По умолчанию true
    ignore_cooldown: true
    # Должен ли кулдаун применяться ко всем предметам из данной группы при использовании любого из них.
    # По умолчанию false.
    # Не распространится на все зелья, если было использовано конкретное, поскольку там используется не-ванильный кулдаун.
    apply_to_all: true
    # Должны ли мы применять кулдаун на предметы только если игрок находится в PVP режиме?
    # Плагин авторматически выберет необходимый плагин.
    apply_only_in_pvp: false
    