name: ${project.name}
main: ru.overwrite.itemcooldowns.ItemCooldowns
author: OverwriteMC
api-version: 1.16
version: ${project.version}
softdepend: [AntiRelog, PowerAntiRelog, CombatLogX, GreatCombat]
commands:
  advanceditemcooldowns:
    permission: itemcooldown.admin
    aliases: [itemcooldowns]
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8